import type { StoreData } from "./types";

const now = new Date("2026-09-22T10:00:00+05:30");
const hoursAgo = (h: number) =>
  new Date(now.getTime() - h * 60 * 60 * 1000).toISOString();
const daysAgo = (d: number) =>
  new Date(now.getTime() - d * 24 * 60 * 60 * 1000).toISOString();
const daysFromNow = (d: number) =>
  new Date(now.getTime() + d * 24 * 60 * 60 * 1000).toISOString();

export const seedData: StoreData = {
  team: [
    {
      id: "tm_beena",
      name: "Beena",
      role: "founder",
      kras: ["Vision & IP", "VIP clients", "Team training", "Strategy"],
      kpis: [
        { metric: "Unplanned interruptions / week", target: "trending to 0 below 🔴" },
        { metric: "% closes without Beena", target: ">70%" },
      ],
      decision_authority: "Vision, partnerships, VIP coaching, IP creation only",
    },
    {
      id: "tm_priya",
      name: "Priya Shah",
      role: "sales_closer",
      kras: ["Run discovery + close", "Score every call in 24h"],
      kpis: [
        { metric: "Close rate", target: "35%" },
        { metric: "Calls scored <24h", target: "100%" },
      ],
      decision_authority: "Discount up to 10%; escalate high-value / stuck deals",
      certified_closer: true,
    },
    {
      id: "tm_arjun",
      name: "Arjun Mehta",
      role: "setter",
      kras: ["Qualify leads", "Book appointments", "No-show recovery"],
      kpis: [
        { metric: "Leads touched <24h", target: "100%" },
        { metric: "Show-up rate", target: "70%" },
      ],
      decision_authority: "Qualify / disqualify; reschedule no-shows",
    },
    {
      id: "tm_neha",
      name: "Neha Kapoor",
      role: "community_manager",
      kras: ["Triage questions", "Hit SLA", "FAQ from repeats"],
      kpis: [
        { metric: "Answered within SLA", target: "95%" },
        { metric: "🔴 escalations / week", target: "<5" },
      ],
      decision_authority: "🟢 routine answers; escalate 🟡 to mentor, 🔴 to Beena",
    },
    {
      id: "tm_ravi",
      name: "Ravi Iyer",
      role: "mentor",
      kras: ["Delivery sessions", "Implementation reviews", "🟡 complex issues"],
      kpis: [
        { metric: "% delivery steps without Beena", target: ">85%" },
        { metric: "At-risk interventions <48h", target: "100%" },
      ],
      decision_authority: "All non-Beena-only delivery; complex community questions",
    },
    {
      id: "tm_sana",
      name: "Sana Ali",
      role: "ops",
      kras: ["Pipeline hygiene", "Onboarding completion", "Reporting freshness"],
      kpis: [
        { metric: "Dashboard freshness", target: "<24h" },
        { metric: "Onboarding auto-complete", target: "100%" },
      ],
      decision_authority: "Process changes within OS SOPs; escalate tool/budget",
    },
  ],

  campaigns: [
    {
      id: "cmp_ig_magnet",
      name: "IG Lead Magnet - Coach Clarity PDF",
      channel: "instagram",
      type: "lead_magnet",
      start_date: "2026-09-01",
      end_date: "2026-09-30",
      total_cost: 0,
    },
    {
      id: "cmp_fb_challenge",
      name: "FB 5-Day Challenge",
      channel: "facebook",
      type: "challenge",
      start_date: "2026-09-10",
      end_date: "2026-09-20",
      total_cost: 18500,
    },
    {
      id: "cmp_li_webinar",
      name: "LinkedIn Webinar - Scale Without Burnout",
      channel: "linkedin",
      type: "webinar",
      start_date: "2026-09-15",
      end_date: "2026-09-22",
      total_cost: 4200,
    },
    {
      id: "cmp_paid_ads",
      name: "Meta Ads - Business Coaching Offer",
      channel: "paid_ad",
      type: "lead_magnet",
      start_date: "2026-09-01",
      end_date: "2026-09-30",
      total_cost: 32000,
    },
  ],

  leads: [
    {
      id: "lead_01",
      name: "Ananya Rao",
      contact: "ananya@example.com",
      source: "instagram",
      campaign_id: "cmp_ig_magnet",
      cost: 0,
      first_touch_date: daysAgo(2),
      last_touch_date: hoursAgo(6),
      qualification_status: "qualified",
      lead_score: 78,
      assigned_setter: "tm_arjun",
      current_stage: "booked",
      program_interest: "business_coaching",
      referred_by: null,
    },
    {
      id: "lead_02",
      name: "Vikram Patel",
      contact: "+91 98765 43210",
      source: "paid_ad",
      campaign_id: "cmp_paid_ads",
      cost: 420,
      first_touch_date: hoursAgo(8),
      last_touch_date: hoursAgo(7),
      qualification_status: "not_qualified",
      lead_score: 42,
      assigned_setter: "tm_arjun",
      current_stage: "nurturing",
      program_interest: "life_accelerator",
      referred_by: null,
    },
    {
      id: "lead_03",
      name: "Meera Joshi",
      contact: "meera@coachstudio.in",
      source: "linkedin",
      campaign_id: "cmp_li_webinar",
      cost: 95,
      first_touch_date: daysAgo(5),
      last_touch_date: daysAgo(1),
      qualification_status: "qualified",
      lead_score: 86,
      assigned_setter: "tm_arjun",
      current_stage: "attended",
      program_interest: "business_coaching",
      referred_by: null,
    },
    {
      id: "lead_04",
      name: "Kabir Singh",
      contact: "kabir@growthlab.io",
      source: "facebook",
      campaign_id: "cmp_fb_challenge",
      cost: 210,
      first_touch_date: daysAgo(12),
      last_touch_date: daysAgo(10),
      qualification_status: "qualified",
      lead_score: 91,
      assigned_setter: "tm_arjun",
      current_stage: "won",
      program_interest: "business_coaching",
      referred_by: null,
    },
    {
      id: "lead_05",
      name: "Diya Nair",
      contact: "diya@example.com",
      source: "referral",
      campaign_id: "cmp_ig_magnet",
      cost: 0,
      first_touch_date: daysAgo(1),
      last_touch_date: hoursAgo(20),
      qualification_status: "not_qualified",
      lead_score: 55,
      assigned_setter: "tm_arjun",
      current_stage: "new",
      program_interest: "low_ticket",
      referred_by: "mem_01",
    },
    {
      id: "lead_06",
      name: "Rohan Desai",
      contact: "rohan@example.com",
      source: "organic",
      campaign_id: "cmp_ig_magnet",
      cost: 0,
      first_touch_date: daysAgo(3),
      last_touch_date: daysAgo(3),
      qualification_status: "not_qualified",
      lead_score: 28,
      assigned_setter: null,
      current_stage: "new",
      program_interest: "life_accelerator",
      referred_by: null,
    },
    {
      id: "lead_07",
      name: "Ishita Verma",
      contact: "ishita@example.com",
      source: "paid_ad",
      campaign_id: "cmp_paid_ads",
      cost: 380,
      first_touch_date: daysAgo(7),
      last_touch_date: daysAgo(2),
      qualification_status: "qualified",
      lead_score: 74,
      assigned_setter: "tm_arjun",
      current_stage: "confirmed",
      program_interest: "business_coaching",
      referred_by: null,
    },
    {
      id: "lead_08",
      name: "Aditya Khan",
      contact: "aditya@example.com",
      source: "facebook",
      campaign_id: "cmp_fb_challenge",
      cost: 180,
      first_touch_date: daysAgo(9),
      last_touch_date: daysAgo(4),
      qualification_status: "disqualified",
      lead_score: 18,
      assigned_setter: "tm_arjun",
      current_stage: "lost",
      program_interest: "low_ticket",
      referred_by: null,
    },
  ],

  appointments: [
    {
      id: "apt_01",
      lead_id: "lead_01",
      scheduled_at: daysFromNow(1),
      status: "booked",
      reminder_sent: false,
      owner: "tm_priya",
      no_show_follow_up_at: null,
    },
    {
      id: "apt_02",
      lead_id: "lead_03",
      scheduled_at: hoursAgo(26),
      status: "attended",
      reminder_sent: true,
      owner: "tm_priya",
      no_show_follow_up_at: null,
    },
    {
      id: "apt_03",
      lead_id: "lead_07",
      scheduled_at: daysFromNow(0.4),
      status: "confirmed",
      reminder_sent: true,
      owner: "tm_priya",
      no_show_follow_up_at: null,
    },
    {
      id: "apt_04",
      lead_id: "lead_04",
      scheduled_at: daysAgo(10),
      status: "attended",
      reminder_sent: true,
      owner: "tm_priya",
      no_show_follow_up_at: null,
    },
  ],

  sales_calls: [
    {
      id: "call_01",
      appointment_id: "apt_02",
      closer: "tm_priya",
      recording_url: "https://example.com/recordings/call_01",
      scorecard: {
        discovery: 4,
        qualification: 5,
        offer: 4,
        objection_handling: 3,
        next_step: 5,
      },
      outcome: "follow_up",
      escalated: false,
      escalation_reason: null,
      scored_at: hoursAgo(4),
    },
    {
      id: "call_02",
      appointment_id: "apt_04",
      closer: "tm_priya",
      recording_url: "https://example.com/recordings/call_02",
      scorecard: {
        discovery: 5,
        qualification: 5,
        offer: 5,
        objection_handling: 4,
        next_step: 5,
      },
      outcome: "won",
      escalated: false,
      escalation_reason: null,
      scored_at: daysAgo(9),
    },
  ],

  members: [
    {
      id: "mem_01",
      lead_id: "lead_04",
      name: "Kabir Singh",
      program: "business_coaching",
      stage: 2,
      onboarding_status: "complete",
      onboarding_day: 7,
      community_channel_id: "skool_kabir",
      coach_assigned: "tm_ravi",
      health_status: "on_track",
      health_score: 84,
      payment_status: "current",
      payment_frequency: "monthly",
      attendance_rate: 90,
      engagement_score: 80,
      implementation_score: 82,
      joined_at: daysAgo(9),
    },
    {
      id: "mem_02",
      lead_id: "lead_win_legacy",
      name: "Sneha Reddy",
      program: "life_accelerator",
      stage: 3,
      onboarding_status: "complete",
      onboarding_day: 7,
      community_channel_id: "skool_sneha",
      coach_assigned: "tm_ravi",
      health_status: "needs_intervention",
      health_score: 58,
      payment_status: "current",
      payment_frequency: "installment",
      attendance_rate: 55,
      engagement_score: 50,
      implementation_score: 70,
      joined_at: daysAgo(45),
    },
    {
      id: "mem_03",
      lead_id: "lead_win_legacy2",
      name: "Farhan Qureshi",
      program: "business_coaching",
      stage: 1,
      onboarding_status: "in_progress",
      onboarding_day: 3,
      community_channel_id: "skool_farhan",
      coach_assigned: "tm_ravi",
      health_status: "on_track",
      health_score: 72,
      payment_status: "current",
      payment_frequency: "one_time",
      attendance_rate: 100,
      engagement_score: 65,
      implementation_score: 50,
      joined_at: daysAgo(3),
    },
    {
      id: "mem_04",
      lead_id: "lead_win_legacy3",
      name: "Lata Menon",
      program: "business_coaching",
      stage: 4,
      onboarding_status: "complete",
      onboarding_day: 7,
      community_channel_id: "skool_lata",
      coach_assigned: "tm_ravi",
      health_status: "at_risk",
      health_score: 34,
      payment_status: "overdue",
      payment_frequency: "monthly",
      attendance_rate: 20,
      engagement_score: 25,
      implementation_score: 40,
      joined_at: daysAgo(90),
    },
  ],

  interactions: [
    {
      id: "int_01",
      member_id: "mem_01",
      subject: "Where do I find Module 2 worksheets?",
      channel: "community",
      type: "question",
      tier: "routine",
      handled_by: "tm_neha",
      response_time_minutes: 22,
      sla_minutes: 120,
      resolved: true,
      resolved_at: hoursAgo(5),
      created_at: hoursAgo(6),
      os_source: "community",
    },
    {
      id: "int_02",
      member_id: "mem_02",
      subject: "Stuck on pricing offer for my clients",
      channel: "community",
      type: "question",
      tier: "complex",
      handled_by: "tm_ravi",
      response_time_minutes: 95,
      sla_minutes: 240,
      resolved: true,
      resolved_at: hoursAgo(12),
      created_at: hoursAgo(14),
      os_source: "community",
    },
    {
      id: "int_03",
      member_id: "mem_04",
      subject: "Considering pausing - payment + results concerns",
      channel: "whatsapp",
      type: "escalation",
      tier: "critical",
      handled_by: null,
      response_time_minutes: null,
      sla_minutes: 60,
      resolved: false,
      resolved_at: null,
      created_at: hoursAgo(3),
      os_source: "client_success",
    },
    {
      id: "int_04",
      member_id: "mem_03",
      subject: "How do I join the live session?",
      channel: "whatsapp",
      type: "question",
      tier: "routine",
      handled_by: null,
      response_time_minutes: null,
      sla_minutes: 120,
      resolved: false,
      resolved_at: null,
      created_at: hoursAgo(3.5),
      os_source: "community",
    },
    {
      id: "int_05",
      member_id: null,
      subject: "High-value prospect wants custom enterprise package",
      channel: "email",
      type: "escalation",
      tier: "critical",
      handled_by: null,
      response_time_minutes: null,
      sla_minutes: 120,
      resolved: false,
      resolved_at: null,
      created_at: hoursAgo(1),
      os_source: "sales",
    },
  ],

  revenue: [
    {
      id: "rev_01",
      member_id: "mem_01",
      program: "business_coaching",
      amount: 150000,
      date: "2026-09-12",
      payment_method: "UPI",
      recurring: true,
      next_billing_date: "2026-10-12",
      closer: "tm_priya",
    },
    {
      id: "rev_02",
      member_id: "mem_02",
      program: "life_accelerator",
      amount: 45000,
      date: "2026-08-01",
      payment_method: "Card",
      recurring: true,
      next_billing_date: "2026-10-01",
      closer: "tm_priya",
    },
    {
      id: "rev_03",
      member_id: "mem_03",
      program: "business_coaching",
      amount: 150000,
      date: "2026-09-19",
      payment_method: "Bank transfer",
      recurring: false,
      next_billing_date: null,
      closer: "tm_priya",
    },
    {
      id: "rev_04",
      member_id: "mem_04",
      program: "business_coaching",
      amount: 50000,
      date: "2026-06-20",
      payment_method: "UPI",
      recurring: true,
      next_billing_date: "2026-09-20",
      closer: "tm_beena",
    },
  ],

  testimonials: [
    {
      id: "tst_01",
      member_id: "mem_01",
      trigger_event: "milestone",
      sent_at: daysAgo(2),
      permission_granted: true,
      format: "written",
      status: "received",
      content:
        "Closed my first INR 2L month after Module 2 - the offer framework alone paid for the program.",
    },
    {
      id: "tst_02",
      member_id: "mem_02",
      trigger_event: "milestone",
      sent_at: daysAgo(1),
      permission_granted: false,
      format: "video",
      status: "requested",
      content: null,
    },
  ],

  referrals: [
    {
      id: "ref_01",
      referring_member_id: "mem_01",
      referred_lead_id: "lead_05",
      reward_status: "pending",
    },
  ],

  delivery_steps: [
    {
      id: "del_01",
      module: "Module 1 - Foundation",
      step: "Orientation live",
      owner_tier: "team",
      sop_url: "/sops/orientation",
    },
    {
      id: "del_02",
      module: "Module 1 - Foundation",
      step: "Welcome WhatsApp + access",
      owner_tier: "automated",
      sop_url: "/sops/welcome-automation",
    },
    {
      id: "del_03",
      module: "Module 2 - Offer",
      step: "Offer teardown workshop",
      owner_tier: "team",
      sop_url: "/sops/offer-workshop",
    },
    {
      id: "del_04",
      module: "Module 3 - Sales",
      step: "Hot-seat sales coaching",
      owner_tier: "beena_only",
      sop_url: "/sops/hotseat",
    },
    {
      id: "del_05",
      module: "Module 4 - Scale",
      step: "Implementation checklist nudge",
      owner_tier: "automated",
      sop_url: "/sops/impl-nudge",
    },
    {
      id: "del_06",
      module: "Module 4 - Scale",
      step: "Results review call",
      owner_tier: "team",
      sop_url: "/sops/results-review",
    },
  ],

  metrics: [
    {
      id: "m1",
      os_source: "marketing",
      metric_name: "Cost per lead (blended)",
      value: 312,
      period: "weekly",
      computed_at: hoursAgo(2),
    },
    {
      id: "m2",
      os_source: "lead",
      metric_name: "% nurtured within 24h",
      value: 87.5,
      period: "weekly",
      computed_at: hoursAgo(2),
    },
    {
      id: "m3",
      os_source: "appointment",
      metric_name: "Show-up rate",
      value: 75,
      period: "weekly",
      computed_at: hoursAgo(2),
    },
    {
      id: "m4",
      os_source: "sales",
      metric_name: "% closes without Beena",
      value: 100,
      period: "monthly",
      computed_at: hoursAgo(2),
    },
    {
      id: "m5",
      os_source: "onboarding",
      metric_name: "% completing 7 touchpoints",
      value: 75,
      period: "monthly",
      computed_at: hoursAgo(2),
    },
    {
      id: "m6",
      os_source: "delivery",
      metric_name: "% steps not requiring Beena",
      value: 83,
      period: "monthly",
      computed_at: hoursAgo(2),
    },
    {
      id: "m7",
      os_source: "community",
      metric_name: "% answered within SLA",
      value: 75,
      period: "weekly",
      computed_at: hoursAgo(2),
    },
    {
      id: "m8",
      os_source: "client_success",
      metric_name: "% at-risk recovered",
      value: 40,
      period: "monthly",
      computed_at: hoursAgo(2),
    },
    {
      id: "m9",
      os_source: "testimonial",
      metric_name: "Response rate",
      value: 50,
      period: "monthly",
      computed_at: hoursAgo(2),
    },
    {
      id: "m10",
      os_source: "referral",
      metric_name: "Referral rate",
      value: 25,
      period: "monthly",
      computed_at: hoursAgo(2),
    },
  ],
};
